# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nekerafa/Documentos/Proyectos/lua-raspi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nekerafa/Documentos/Proyectos/lua-raspi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nekerafa/Documentos/Proyectos/lua-raspi/CMakeFiles /home/nekerafa/Documentos/Proyectos/lua-raspi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nekerafa/Documentos/Proyectos/lua-raspi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lraspi.0.0.1

# Build rule for target.
lraspi.0.0.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lraspi.0.0.1
.PHONY : lraspi.0.0.1

# fast build rule for target.
lraspi.0.0.1/fast:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/build
.PHONY : lraspi.0.0.1/fast

#=============================================================================
# Target rules for targets named lraspi

# Build rule for target.
lraspi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lraspi
.PHONY : lraspi

# fast build rule for target.
lraspi/fast:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/build
.PHONY : lraspi/fast

src/common/exception.o: src/common/exception.cc.o

.PHONY : src/common/exception.o

# target to build an object file
src/common/exception.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/exception.cc.o
.PHONY : src/common/exception.cc.o

src/common/exception.i: src/common/exception.cc.i

.PHONY : src/common/exception.i

# target to preprocess a source file
src/common/exception.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/exception.cc.i
.PHONY : src/common/exception.cc.i

src/common/exception.s: src/common/exception.cc.s

.PHONY : src/common/exception.s

# target to generate assembly for a file
src/common/exception.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/exception.cc.s
.PHONY : src/common/exception.cc.s

src/common/object.o: src/common/object.cc.o

.PHONY : src/common/object.o

# target to build an object file
src/common/object.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/object.cc.o
.PHONY : src/common/object.cc.o

src/common/object.i: src/common/object.cc.i

.PHONY : src/common/object.i

# target to preprocess a source file
src/common/object.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/object.cc.i
.PHONY : src/common/object.cc.i

src/common/object.s: src/common/object.cc.s

.PHONY : src/common/object.s

# target to generate assembly for a file
src/common/object.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/object.cc.s
.PHONY : src/common/object.cc.s

src/common/type.o: src/common/type.cc.o

.PHONY : src/common/type.o

# target to build an object file
src/common/type.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/type.cc.o
.PHONY : src/common/type.cc.o

src/common/type.i: src/common/type.cc.i

.PHONY : src/common/type.i

# target to preprocess a source file
src/common/type.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/type.cc.i
.PHONY : src/common/type.cc.i

src/common/type.s: src/common/type.cc.s

.PHONY : src/common/type.s

# target to generate assembly for a file
src/common/type.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/common/type.cc.s
.PHONY : src/common/type.cc.s

src/interface/explorer.o: src/interface/explorer.cc.o

.PHONY : src/interface/explorer.o

# target to build an object file
src/interface/explorer.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/interface/explorer.cc.o
.PHONY : src/interface/explorer.cc.o

src/interface/explorer.i: src/interface/explorer.cc.i

.PHONY : src/interface/explorer.i

# target to preprocess a source file
src/interface/explorer.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/interface/explorer.cc.i
.PHONY : src/interface/explorer.cc.i

src/interface/explorer.s: src/interface/explorer.cc.s

.PHONY : src/interface/explorer.s

# target to generate assembly for a file
src/interface/explorer.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/interface/explorer.cc.s
.PHONY : src/interface/explorer.cc.s

src/lraspi.o: src/lraspi.cc.o

.PHONY : src/lraspi.o

# target to build an object file
src/lraspi.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/lraspi.cc.o
.PHONY : src/lraspi.cc.o

src/lraspi.i: src/lraspi.cc.i

.PHONY : src/lraspi.i

# target to preprocess a source file
src/lraspi.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/lraspi.cc.i
.PHONY : src/lraspi.cc.i

src/lraspi.s: src/lraspi.cc.s

.PHONY : src/lraspi.s

# target to generate assembly for a file
src/lraspi.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.dir/build.make CMakeFiles/lraspi.dir/src/lraspi.cc.s
.PHONY : src/lraspi.cc.s

src/lraspi/lauxlib.o: src/lraspi/lauxlib.cc.o

.PHONY : src/lraspi/lauxlib.o

# target to build an object file
src/lraspi/lauxlib.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lauxlib.cc.o
.PHONY : src/lraspi/lauxlib.cc.o

src/lraspi/lauxlib.i: src/lraspi/lauxlib.cc.i

.PHONY : src/lraspi/lauxlib.i

# target to preprocess a source file
src/lraspi/lauxlib.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lauxlib.cc.i
.PHONY : src/lraspi/lauxlib.cc.i

src/lraspi/lauxlib.s: src/lraspi/lauxlib.cc.s

.PHONY : src/lraspi/lauxlib.s

# target to generate assembly for a file
src/lraspi/lauxlib.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lauxlib.cc.s
.PHONY : src/lraspi/lauxlib.cc.s

src/lraspi/lcolor.o: src/lraspi/lcolor.cc.o

.PHONY : src/lraspi/lcolor.o

# target to build an object file
src/lraspi/lcolor.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lcolor.cc.o
.PHONY : src/lraspi/lcolor.cc.o

src/lraspi/lcolor.i: src/lraspi/lcolor.cc.i

.PHONY : src/lraspi/lcolor.i

# target to preprocess a source file
src/lraspi/lcolor.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lcolor.cc.i
.PHONY : src/lraspi/lcolor.cc.i

src/lraspi/lcolor.s: src/lraspi/lcolor.cc.s

.PHONY : src/lraspi/lcolor.s

# target to generate assembly for a file
src/lraspi/lcolor.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lcolor.cc.s
.PHONY : src/lraspi/lcolor.cc.s

src/lraspi/lfont.o: src/lraspi/lfont.cc.o

.PHONY : src/lraspi/lfont.o

# target to build an object file
src/lraspi/lfont.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lfont.cc.o
.PHONY : src/lraspi/lfont.cc.o

src/lraspi/lfont.i: src/lraspi/lfont.cc.i

.PHONY : src/lraspi/lfont.i

# target to preprocess a source file
src/lraspi/lfont.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lfont.cc.i
.PHONY : src/lraspi/lfont.cc.i

src/lraspi/lfont.s: src/lraspi/lfont.cc.s

.PHONY : src/lraspi/lfont.s

# target to generate assembly for a file
src/lraspi/lfont.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lfont.cc.s
.PHONY : src/lraspi/lfont.cc.s

src/lraspi/limage.o: src/lraspi/limage.cc.o

.PHONY : src/lraspi/limage.o

# target to build an object file
src/lraspi/limage.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/limage.cc.o
.PHONY : src/lraspi/limage.cc.o

src/lraspi/limage.i: src/lraspi/limage.cc.i

.PHONY : src/lraspi/limage.i

# target to preprocess a source file
src/lraspi/limage.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/limage.cc.i
.PHONY : src/lraspi/limage.cc.i

src/lraspi/limage.s: src/lraspi/limage.cc.s

.PHONY : src/lraspi/limage.s

# target to generate assembly for a file
src/lraspi/limage.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/limage.cc.s
.PHONY : src/lraspi/limage.cc.s

src/lraspi/lscreen.o: src/lraspi/lscreen.cc.o

.PHONY : src/lraspi/lscreen.o

# target to build an object file
src/lraspi/lscreen.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lscreen.cc.o
.PHONY : src/lraspi/lscreen.cc.o

src/lraspi/lscreen.i: src/lraspi/lscreen.cc.i

.PHONY : src/lraspi/lscreen.i

# target to preprocess a source file
src/lraspi/lscreen.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lscreen.cc.i
.PHONY : src/lraspi/lscreen.cc.i

src/lraspi/lscreen.s: src/lraspi/lscreen.cc.s

.PHONY : src/lraspi/lscreen.s

# target to generate assembly for a file
src/lraspi/lscreen.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/lraspi/lscreen.cc.s
.PHONY : src/lraspi/lscreen.cc.s

src/modules/color/color.o: src/modules/color/color.cc.o

.PHONY : src/modules/color/color.o

# target to build an object file
src/modules/color/color.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color.cc.o
.PHONY : src/modules/color/color.cc.o

src/modules/color/color.i: src/modules/color/color.cc.i

.PHONY : src/modules/color/color.i

# target to preprocess a source file
src/modules/color/color.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color.cc.i
.PHONY : src/modules/color/color.cc.i

src/modules/color/color.s: src/modules/color/color.cc.s

.PHONY : src/modules/color/color.s

# target to generate assembly for a file
src/modules/color/color.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color.cc.s
.PHONY : src/modules/color/color.cc.s

src/modules/color/color_mod.o: src/modules/color/color_mod.cc.o

.PHONY : src/modules/color/color_mod.o

# target to build an object file
src/modules/color/color_mod.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color_mod.cc.o
.PHONY : src/modules/color/color_mod.cc.o

src/modules/color/color_mod.i: src/modules/color/color_mod.cc.i

.PHONY : src/modules/color/color_mod.i

# target to preprocess a source file
src/modules/color/color_mod.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color_mod.cc.i
.PHONY : src/modules/color/color_mod.cc.i

src/modules/color/color_mod.s: src/modules/color/color_mod.cc.s

.PHONY : src/modules/color/color_mod.s

# target to generate assembly for a file
src/modules/color/color_mod.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/color/color_mod.cc.s
.PHONY : src/modules/color/color_mod.cc.s

src/modules/font/font.o: src/modules/font/font.cc.o

.PHONY : src/modules/font/font.o

# target to build an object file
src/modules/font/font.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font.cc.o
.PHONY : src/modules/font/font.cc.o

src/modules/font/font.i: src/modules/font/font.cc.i

.PHONY : src/modules/font/font.i

# target to preprocess a source file
src/modules/font/font.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font.cc.i
.PHONY : src/modules/font/font.cc.i

src/modules/font/font.s: src/modules/font/font.cc.s

.PHONY : src/modules/font/font.s

# target to generate assembly for a file
src/modules/font/font.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font.cc.s
.PHONY : src/modules/font/font.cc.s

src/modules/font/font_mod.o: src/modules/font/font_mod.cc.o

.PHONY : src/modules/font/font_mod.o

# target to build an object file
src/modules/font/font_mod.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font_mod.cc.o
.PHONY : src/modules/font/font_mod.cc.o

src/modules/font/font_mod.i: src/modules/font/font_mod.cc.i

.PHONY : src/modules/font/font_mod.i

# target to preprocess a source file
src/modules/font/font_mod.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font_mod.cc.i
.PHONY : src/modules/font/font_mod.cc.i

src/modules/font/font_mod.s: src/modules/font/font_mod.cc.s

.PHONY : src/modules/font/font_mod.s

# target to generate assembly for a file
src/modules/font/font_mod.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/font/font_mod.cc.s
.PHONY : src/modules/font/font_mod.cc.s

src/modules/image/image.o: src/modules/image/image.cc.o

.PHONY : src/modules/image/image.o

# target to build an object file
src/modules/image/image.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image.cc.o
.PHONY : src/modules/image/image.cc.o

src/modules/image/image.i: src/modules/image/image.cc.i

.PHONY : src/modules/image/image.i

# target to preprocess a source file
src/modules/image/image.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image.cc.i
.PHONY : src/modules/image/image.cc.i

src/modules/image/image.s: src/modules/image/image.cc.s

.PHONY : src/modules/image/image.s

# target to generate assembly for a file
src/modules/image/image.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image.cc.s
.PHONY : src/modules/image/image.cc.s

src/modules/image/image_mod.o: src/modules/image/image_mod.cc.o

.PHONY : src/modules/image/image_mod.o

# target to build an object file
src/modules/image/image_mod.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image_mod.cc.o
.PHONY : src/modules/image/image_mod.cc.o

src/modules/image/image_mod.i: src/modules/image/image_mod.cc.i

.PHONY : src/modules/image/image_mod.i

# target to preprocess a source file
src/modules/image/image_mod.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image_mod.cc.i
.PHONY : src/modules/image/image_mod.cc.i

src/modules/image/image_mod.s: src/modules/image/image_mod.cc.s

.PHONY : src/modules/image/image_mod.s

# target to generate assembly for a file
src/modules/image/image_mod.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/image_mod.cc.s
.PHONY : src/modules/image/image_mod.cc.s

src/modules/image/text.o: src/modules/image/text.cc.o

.PHONY : src/modules/image/text.o

# target to build an object file
src/modules/image/text.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/text.cc.o
.PHONY : src/modules/image/text.cc.o

src/modules/image/text.i: src/modules/image/text.cc.i

.PHONY : src/modules/image/text.i

# target to preprocess a source file
src/modules/image/text.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/text.cc.i
.PHONY : src/modules/image/text.cc.i

src/modules/image/text.s: src/modules/image/text.cc.s

.PHONY : src/modules/image/text.s

# target to generate assembly for a file
src/modules/image/text.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/text.cc.s
.PHONY : src/modules/image/text.cc.s

src/modules/image/texture.o: src/modules/image/texture.cc.o

.PHONY : src/modules/image/texture.o

# target to build an object file
src/modules/image/texture.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/texture.cc.o
.PHONY : src/modules/image/texture.cc.o

src/modules/image/texture.i: src/modules/image/texture.cc.i

.PHONY : src/modules/image/texture.i

# target to preprocess a source file
src/modules/image/texture.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/texture.cc.i
.PHONY : src/modules/image/texture.cc.i

src/modules/image/texture.s: src/modules/image/texture.cc.s

.PHONY : src/modules/image/texture.s

# target to generate assembly for a file
src/modules/image/texture.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/image/texture.cc.s
.PHONY : src/modules/image/texture.cc.s

src/modules/lraspi/lraspi.o: src/modules/lraspi/lraspi.cc.o

.PHONY : src/modules/lraspi/lraspi.o

# target to build an object file
src/modules/lraspi/lraspi.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/lraspi/lraspi.cc.o
.PHONY : src/modules/lraspi/lraspi.cc.o

src/modules/lraspi/lraspi.i: src/modules/lraspi/lraspi.cc.i

.PHONY : src/modules/lraspi/lraspi.i

# target to preprocess a source file
src/modules/lraspi/lraspi.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/lraspi/lraspi.cc.i
.PHONY : src/modules/lraspi/lraspi.cc.i

src/modules/lraspi/lraspi.s: src/modules/lraspi/lraspi.cc.s

.PHONY : src/modules/lraspi/lraspi.s

# target to generate assembly for a file
src/modules/lraspi/lraspi.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/lraspi/lraspi.cc.s
.PHONY : src/modules/lraspi/lraspi.cc.s

src/modules/screen/screen_mod.o: src/modules/screen/screen_mod.cc.o

.PHONY : src/modules/screen/screen_mod.o

# target to build an object file
src/modules/screen/screen_mod.cc.o:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/screen/screen_mod.cc.o
.PHONY : src/modules/screen/screen_mod.cc.o

src/modules/screen/screen_mod.i: src/modules/screen/screen_mod.cc.i

.PHONY : src/modules/screen/screen_mod.i

# target to preprocess a source file
src/modules/screen/screen_mod.cc.i:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/screen/screen_mod.cc.i
.PHONY : src/modules/screen/screen_mod.cc.i

src/modules/screen/screen_mod.s: src/modules/screen/screen_mod.cc.s

.PHONY : src/modules/screen/screen_mod.s

# target to generate assembly for a file
src/modules/screen/screen_mod.cc.s:
	$(MAKE) -f CMakeFiles/lraspi.0.0.1.dir/build.make CMakeFiles/lraspi.0.0.1.dir/src/modules/screen/screen_mod.cc.s
.PHONY : src/modules/screen/screen_mod.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lraspi.0.0.1"
	@echo "... rebuild_cache"
	@echo "... lraspi"
	@echo "... src/common/exception.o"
	@echo "... src/common/exception.i"
	@echo "... src/common/exception.s"
	@echo "... src/common/object.o"
	@echo "... src/common/object.i"
	@echo "... src/common/object.s"
	@echo "... src/common/type.o"
	@echo "... src/common/type.i"
	@echo "... src/common/type.s"
	@echo "... src/interface/explorer.o"
	@echo "... src/interface/explorer.i"
	@echo "... src/interface/explorer.s"
	@echo "... src/lraspi.o"
	@echo "... src/lraspi.i"
	@echo "... src/lraspi.s"
	@echo "... src/lraspi/lauxlib.o"
	@echo "... src/lraspi/lauxlib.i"
	@echo "... src/lraspi/lauxlib.s"
	@echo "... src/lraspi/lcolor.o"
	@echo "... src/lraspi/lcolor.i"
	@echo "... src/lraspi/lcolor.s"
	@echo "... src/lraspi/lfont.o"
	@echo "... src/lraspi/lfont.i"
	@echo "... src/lraspi/lfont.s"
	@echo "... src/lraspi/limage.o"
	@echo "... src/lraspi/limage.i"
	@echo "... src/lraspi/limage.s"
	@echo "... src/lraspi/lscreen.o"
	@echo "... src/lraspi/lscreen.i"
	@echo "... src/lraspi/lscreen.s"
	@echo "... src/modules/color/color.o"
	@echo "... src/modules/color/color.i"
	@echo "... src/modules/color/color.s"
	@echo "... src/modules/color/color_mod.o"
	@echo "... src/modules/color/color_mod.i"
	@echo "... src/modules/color/color_mod.s"
	@echo "... src/modules/font/font.o"
	@echo "... src/modules/font/font.i"
	@echo "... src/modules/font/font.s"
	@echo "... src/modules/font/font_mod.o"
	@echo "... src/modules/font/font_mod.i"
	@echo "... src/modules/font/font_mod.s"
	@echo "... src/modules/image/image.o"
	@echo "... src/modules/image/image.i"
	@echo "... src/modules/image/image.s"
	@echo "... src/modules/image/image_mod.o"
	@echo "... src/modules/image/image_mod.i"
	@echo "... src/modules/image/image_mod.s"
	@echo "... src/modules/image/text.o"
	@echo "... src/modules/image/text.i"
	@echo "... src/modules/image/text.s"
	@echo "... src/modules/image/texture.o"
	@echo "... src/modules/image/texture.i"
	@echo "... src/modules/image/texture.s"
	@echo "... src/modules/lraspi/lraspi.o"
	@echo "... src/modules/lraspi/lraspi.i"
	@echo "... src/modules/lraspi/lraspi.s"
	@echo "... src/modules/screen/screen_mod.o"
	@echo "... src/modules/screen/screen_mod.i"
	@echo "... src/modules/screen/screen_mod.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

